#include "tokens.h"

const char * const lista_tokens[]={    
        "Fim de buffer(EOS)",
        "Erro Lexico",
        "identificador",
        "numero",
        "comentario",
        // operador
        "=",
        "==",
        "!=",
        "<",
        "<=",
        ">",
        ">=",
        "+",
        "-",
        "*",
        "/",
        "||",
        "&&",
        // palavra reservada
        "int",
        "bool", 
        "main",
        "scanf",
        "printf",
        "if",
        "else",
        "while",
        "void",
        "true",
        "false",
        // outros
        "virgula",
        "(",
        ")",
        "{",
        "}",
        ";",
};